### ISSUE TITLE
Saving Videos

### ISSUE THREAD

**Issue by PharaohCola13** [PharaohCola13/GeoExpanse#5]
Save plot animations as mp4 files

**Comment by PharaohCola13** [comment]
Trashing Feature for the time being.

**Comment by PharaohCola13** [comment]
Issue has been resolved

**Comment by PharaohCola13** [comment]
Rotations have been disabled and will be released upon fixing bugs. Sorry :(

**Comment by SharkSorceress** [comment]
Archiving this repository. Hasn't been maintained in some time
